# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PolyvLiveScenesDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'PolyvCloudClassSDK','~> 0.14.0'
  
  pod 'SDWebImage', '3.8.2'
  pod 'MJRefresh', '3.1.15.6'

end
